services:
  wordpress:
    build: .
    container_name: wordpress
    user: "33:33"
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wp-content:/var/www/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      SHELL: "/bin/bash"
      APACHE_DOCUMENT_ROOT: /var/www
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: db
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
